In [1]:
import numpy as np

haystack = np.array([1, 2, 3, 4, 5, 5])
needles = np.array([3, 5])

f'Haystack: {haystack}, Needles: {needles}'

'Haystack: [1 2 3 4 5 5], Needles: [3 5]'

In [2]:
aux = np.concatenate((haystack, needles))
aux

array([1, 2, 3, 4, 5, 5, 3, 5])

In [3]:
# There will be duplicate consecutive values for each 
# intersecting element.
aux.sort()
aux

array([1, 2, 3, 3, 4, 5, 5, 5])

In [4]:
mask = aux[1:] == aux[:-1]
mask

array([False, False,  True, False, False,  True,  True])

In [5]:
intersection = aux[:-1][mask]
intersection

array([3, 5, 5])

In [6]:
np.unique(intersection)

array([3, 5])